name: "Firebase Emulators with Jest"
author: "Xi Ming"
description: "Wraps the firebase-tools CLI and Jest to enable common commands."
branding:
  icon: "package"
  color: "gray-dark"
runs:
  using: "docker"
  image: "Dockerfile"
